---
- name: Git from git-prompt
  git:
    repo: https://github.com/magicmonty/bash-git-prompt.git
    dest: /home/root/.bash-git-prompt
    depth: 1

- name: Add configuration in .bashrc
  lineinfile:
    dest: /root/.bashrc
    line: 'GIT_PROMPT_ONLY_IN_REPO=1'

- name: Add configuration in .bashrc
  lineinfile:
    dest: /root/.bashrc
    line: 'source ~/.bash-git-prompt/gitprompt.sh'
  notify:
    - Load Bashrc

